
# adj1 = input("Nhap tinh tu: ")
# sophong = int(input("Nhap so phong: "))
# tenphong1 = input("Nhap ten phong: ")
# tenphong2 = input("Nhap ten phong: ")
# tenphong3 = input("Nhap ten phong: ")
# nguoi = int(input("Nhap so nguoi: "))
# print(f"Nha toi rat {adj1}")
# print(f"Nha toi co {sophong} phong, gom {tenphong1}, {tenphong2} va {tenphong3}")
# print(f"Gia dinh co {nguoi} nguoi")